name: macos-latest-clang

on: [ push ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
      
    - name: Install dependencies
      run:
        brew install mesa-glu mesalib-glw freeglut
      
    - name: Download copperspice
      run: 
        wget https://download.copperspice.com/copperspice/binary/cs-1.7/copperspice-1.7.4-osx10.16-x64.tar.bz2

    - name: Install copperspice
      run: 
        mkdir third-party/copperspice &&
        tar -xjf copperspice-1.7.4-osx10.16-x64.tar.bz2 --directory third-party/copperspice
        
    - name: Configure CMake
      env: 
        CC: clang
      run: cmake -DCMAKE_PREFIX_PATH=${{github.workspace}}/third-party/copperspice/lib/cmake/CopperSpice -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
      
